// Type declarations for @itslil/lil2-micromark. Generated by lilscript-work/lil2/release/types.mjs.

/**
 * Compiles markdown to HTML, as micromark 4 does: the same HTML for the same input.
 * @param value Markdown.
 * @param allowDangerousHtml Keep raw HTML in the output (micromark's `allowDangerousHtml`); default false.
 * @param allowDangerousProtocol Keep links with any protocol (micromark's `allowDangerousProtocol`); default false.
 */
export declare function micromark(value: string, allowDangerousHtml?: boolean, allowDangerousProtocol?: boolean): string
